VollyTest/Controllers/Mvc/OrganizationsController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VollyTest.Models;

namespace VollyTest.Controllers.Mvc
{
    public class OrganizationsController : Controller
    {
        private readonly VollyModel _context;

        public OrganizationsController(VollyModel context)
        {
            _context = context;
        }

        // GET: Organizations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Organizations.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile postedFile)
        {
            using (var reader = new StreamReader(postedFile.OpenReadStream()))
            {
                CsvReader csvReader = new CsvReader(reader);
                csvReader.Configuration.MissingFieldFound = null;
                csvReader.Configuration.HeaderValidated = null;
                csvReader.Configuration.BadDataFound = null;
                IEnumerable<Organization> records = csvReader.GetRecords<Organization>();
                foreach (Organization organization in records)
                {
                    _context.Add(organization);
                }
            }
            await _context.SaveChangesAsync();
            return View(await _context.Organizations.ToListAsync());
        }

        // GET: Organizations/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations
                .SingleOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // GET: Organizations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ContactEmail,PhoneNumber,Address,WebsiteLink,DonateLink,MissionStatement,FullDescription")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                _context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(organization);
        }

        // GET: Organizations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations.SingleOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ContactEmail,PhoneNumber,Address,WebsiteLink,DonateLink,MissionStatement,FullDescription")] Organization organization)
        {
            if (id != organization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(organization);
        }

        // GET: Organizations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations
                .SingleOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organization = await _context.Organizations.SingleOrDefaultAsync(m => m.Id == id);
            _context.Organizations.Remove(organization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationExists(int id)
        {
            return _context.Organizations.Any(e => e.Id == id);
        }
    }
}

VollyTest/Views/Organizations/Create.cshtml
@model VollyTest.Models.Organization

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WebsiteLink" class="control-label"></label>
                <input asp-for="WebsiteLink" class="form-control" />
                <span asp-validation-for="WebsiteLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonateLink" class="control-label"></label>
                <input asp-for="DonateLink" class="form-control" />
                <span asp-validation-for="DonateLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MissionStatement" class="control-label"></label>
                <input asp-for="MissionStatement" class="form-control" />
                <span asp-validation-for="MissionStatement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullDescription" class="control-label"></label>
                <input asp-for="FullDescription" class="form-control" />
                <span asp-validation-for="FullDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VollyTest/Views/Organizations/Delete.cshtml
@model VollyTest.Models.Organization

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DonateLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DonateLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MissionStatement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MissionStatement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VollyTest/Views/Organizations/Details.cshtml
@model VollyTest.Models.Organization

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DonateLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DonateLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MissionStatement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MissionStatement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullDescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VollyTest/Views/Organizations/Edit.cshtml
@model VollyTest.Models.Organization

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WebsiteLink" class="control-label"></label>
                <input asp-for="WebsiteLink" class="form-control" />
                <span asp-validation-for="WebsiteLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonateLink" class="control-label"></label>
                <input asp-for="DonateLink" class="form-control" />
                <span asp-validation-for="DonateLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MissionStatement" class="control-label"></label>
                <input asp-for="MissionStatement" class="form-control" />
                <span asp-validation-for="MissionStatement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullDescription" class="control-label"></label>
                <input asp-for="FullDescription" class="form-control" />
                <span asp-validation-for="FullDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VollyTest/Views/Organizations/Index.cshtml
@model IEnumerable<VollyTest.Models.Organization>

@{
    ViewData["Title"] = "Index";
    string message = (string)ViewData["message"];
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
    <h1>@message</h1>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonateLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MissionStatement)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullDescription)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WebsiteLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonateLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MissionStatement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullDescription)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
    
Upload organizations
@using (Html.BeginForm("Index", "Organizations", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="postedFile" />
    <input type="submit" value="Import" />
}